# The certificate and private key are generated by Casdoor.
resource "casdoor_cert" "acme" {
  name             = "cert-acme"
  display_name     = "Acme cert"
  scope            = "JWT"
  type             = "x509"
  crypto_algorithm = "RS256"
  bit_size         = 4096
  expire_in_years  = 20
}
