// Copyright 2026 The Casdoor Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package provider

const unmanagedNote = "\n\nOnly the attributes set in the configuration are written to Casdoor. The other fields of the object, including the ones not listed here, keep their current values."

var orgOwner = str("owner", "owner", "The organization that the object belongs to.").req().replace()

var adminOwner = str("owner", "owner", "The owner of the object: `admin` for a global object shared by all organizations, or the name of an organization.").defaults("admin").replace()

var objectKinds = []objectKind{
	{
		name:        "organization",
		api:         "organization",
		adminOwned:  true,
		description: "Manages a Casdoor organization." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("website_url", "websiteUrl", "The website URL."),
			str("logo", "logo", "The logo URL."),
			str("logo_dark", "logoDark", "The logo URL for the dark theme."),
			str("favicon", "favicon", "The favicon URL."),
			str("password_type", "passwordType", "How passwords are stored: `plain`, `salt`, `sha512-salt`, `md5-salt`, `bcrypt`, `pbkdf2-salt` or `argon2id`."),
			strList("password_options", "passwordOptions", "The password complexity rules, e.g. `AtLeast6`, `Aa123`, `SpecialChar`, `NoRepeat`."),
			integer("password_expire_days", "passwordExpireDays", "The number of days after which a password expires, 0 means never."),
			integer("password_history_count", "passwordHistoryCount", "The number of recent passwords, the current one included, that cannot be reused."),
			str("password_obfuscator_type", "passwordObfuscatorType", "How the sign-in page obfuscates the password before sending it: `Plain`, `AES` or `DES`."),
			str("password_obfuscator_key", "passwordObfuscatorKey", "The key used to obfuscate the password.").secret(),
			integer("token_retention_days", "tokenRetentionDays", "The number of days expired tokens are kept, 0 means the default of 30."),
			integer("record_retention_days", "recordRetentionDays", "The number of days audit records are kept, 0 means forever."),
			strList("country_codes", "countryCodes", "The country codes allowed for phone numbers, e.g. `US`, `CN`."),
			str("default_avatar", "defaultAvatar", "The default avatar URL of new users."),
			boolean("use_permanent_avatar", "usePermanentAvatar", "Whether avatars from third-party providers are copied to the storage provider."),
			str("default_application", "defaultApplication", "The application used when signing in to the organization without an application."),
			str("default_token_format", "defaultTokenFormat", "The token format of applications created by dynamic client registration."),
			strList("default_token_fields", "defaultTokenFields", "The token fields of applications created by dynamic client registration."),
			str("dcr_policy", "dcrPolicy", "The policy of OAuth dynamic client registration: `open` or `disabled`."),
			strList("user_types", "userTypes", "The user types."),
			strList("tags", "tags", "The user tags."),
			strList("languages", "languages", "The languages of the UI, e.g. `en`, `zh`."),
			str("master_password", "masterPassword", "The master password that signs in as any user of the organization.").password(),
			str("default_password", "defaultPassword", "The default password of users added without a password.").password(),
			str("master_verification_code", "masterVerificationCode", "The master verification code that passes any verification of the organization.").password(),
			integer("init_score", "initScore", "The initial score of new users."),
			boolean("enable_soft_deletion", "enableSoftDeletion", "Whether deleted users are only marked as deleted."),
			boolean("is_profile_public", "isProfilePublic", "Whether user profiles are visible to other users."),
			boolean("use_email_as_username", "useEmailAsUsername", "Whether the email is used as the username at sign-up."),
			boolean("disable_signin", "disableSignin", "Whether signing in to the organization is disabled."),
			boolean("enable_exclusive_signin", "enableExclusiveSignin", "Whether a new sign-in signs the user out of the other sessions."),
			integer("max_sessions", "maxSessions", "The maximum number of concurrent sessions of a user."),
			boolean("disable_console", "disableConsole", "Whether the users of the organization are kept out of the Casdoor console."),
			boolean("has_privilege_consent", "hasPrivilegeConsent", "Whether users other than `admin` can be added to the `built-in` organization."),
			boolean("enable_tour", "enableTour", "Whether the guided tour of the console is shown."),
			str("ip_whitelist", "ipWhitelist", "The IP addresses or CIDRs allowed to sign in, separated by commas."),
			str("trusted_db_hosts", "trustedDbHosts", "The database hosts that the organization may connect to, separated by commas."),
			strList("nav_items", "navItems", "The navigation items shown to the admins of the organization, `all` shows everything."),
			strList("user_nav_items", "userNavItems", "The navigation items shown to the users of the organization, `all` shows everything."),
			strList("widget_items", "widgetItems", "The widgets shown in the header of the console, `all` shows everything."),
			objList("mfa_items", "mfaItems", "The multi-factor authentication methods and whether they are required.",
				str("name", "name", "The MFA method, e.g. `Phone`, `Email` or `App`.").req(),
				str("rule", "rule", "The rule: `Optional`, `Prompted` or `Required`."),
			),
			strList("ldap_attributes", "ldapAttributes", "The user attributes published by the built-in LDAP server."),
			boolean("enable_ldap_password", "enableLdapPassword", "Whether the built-in LDAP server accepts password changes."),
			boolean("enable_radius", "enableRadius", "Whether the built-in RADIUS server serves the organization."),
			str("kerberos_realm", "kerberosRealm", "The Kerberos realm."),
			str("kerberos_kdc_host", "kerberosKdcHost", "The host of the Kerberos KDC."),
			str("kerberos_keytab", "kerberosKeytab", "The Base64-encoded Kerberos keytab.").secret(),
			str("kerberos_service_name", "kerberosServiceName", "The Kerberos service name."),
			integer("mfa_remember_in_hours", "mfaRememberInHours", "The number of hours a passed MFA check is remembered."),
		},
	},
	{
		name:        "application",
		api:         "application",
		adminOwned:  true,
		description: "Manages a Casdoor application, the OAuth 2.0 / OIDC / SAML client that users sign in to." + unmanagedNote,
		fields: []field{
			str("organization", "organization", "The organization whose users sign in to the application.").req(),
			str("display_name", "displayName", "The display name."),
			str("description", "description", "The description."),
			str("logo", "logo", "The logo URL."),
			str("logo_dark", "logoDark", "The logo URL for the dark theme."),
			str("title", "title", "The title of the sign-in pages."),
			str("favicon", "favicon", "The favicon URL."),
			integer("order", "order", "The position of the application in lists."),
			str("homepage_url", "homepageUrl", "The homepage URL."),
			str("category", "category", "The category, e.g. `Default` or `Agent`."),
			str("type", "type", "The type, e.g. `All`, `OIDC`, `OAuth`, `SAML` or `CAS`."),
			strList("tags", "tags", "The tags."),
			str("cert", "cert", "The name of the cert that signs the tokens."),
			str("client_id", "clientId", "The client ID. Generated by Casdoor when not set."),
			str("client_secret", "clientSecret", "The client secret. Generated by Casdoor when not set.").secret(),
			str("client_cert", "clientCert", "The name of the cert that verifies the client."),
			strList("redirect_uris", "redirectUris", "The allowed redirect URIs, which can be regular expressions."),
			str("forced_redirect_origin", "forcedRedirectOrigin", "The origin that the sign-in pages of the application are always served from."),
			str("backchannel_logout_uri", "backchannelLogoutUri", "The OIDC back-channel logout URI that is notified when a user signs out."),
			strList("grant_types", "grantTypes", "The allowed OAuth grant types, e.g. `authorization_code`, `password`, `client_credentials`, `token`, `refresh_token`."),
			str("token_format", "tokenFormat", "The format of the access token, e.g. `JWT`, `JWT-Empty`, `JWT-Custom` or `JWT-Standard`."),
			strList("token_fields", "tokenFields", "The user fields included in a `JWT-Custom` token."),
			str("token_signing_method", "tokenSigningMethod", "The algorithm that signs the tokens: `RS256`, `RS512`, `ES256`, `ES384` or `ES512`."),
			str("token_group_format", "tokenGroupFormat", "How groups appear in the token: empty for `organization/group`, `Name` for group names or `Path` for full group paths."),
			objList("token_attributes", "tokenAttributes", "The custom claims added to a `JWT-Custom` token.",
				str("name", "name", "The name of the claim.").req(),
				str("category", "category", "Where the value comes from: `Static Value` or `Existing Field`."),
				str("value", "value", "The value, or the user field that the value is read from."),
				str("type", "type", "The type of the claim, e.g. `String` or `Array`."),
			),
			float("expire_in_hours", "expireInHours", "The lifetime of the access token, in hours."),
			float("refresh_expire_in_hours", "refreshExpireInHours", "The lifetime of the refresh token, in hours."),
			boolean("disable_refresh_rotation", "disableRefreshRotation", "Whether the refresh token stays the same when it is used, instead of being replaced."),
			integer("cookie_expire_in_hours", "cookieExpireInHours", "The lifetime of the sign-in session cookie, in hours."),
			integer("failed_signin_limit", "failedSigninLimit", "The number of failed sign-in attempts after which the user is frozen, 0 means the default of 5."),
			integer("failed_signin_frozen_time", "failedSigninFrozenTime", "The number of minutes a user stays frozen after reaching the limit, 0 means the default of 15."),
			integer("code_resend_timeout", "codeResendTimeout", "The number of seconds before a verification code can be sent again, 0 means the default."),
			str("ip_whitelist", "ipWhitelist", "The IP addresses or CIDRs allowed to sign in, separated by commas."),
			str("default_group", "defaultGroup", "The group that new users are added to at sign-up."),
			str("default_tag", "defaultTag", "The tag that new users get at sign-up."),
			boolean("enable_password", "enablePassword", "Whether users can sign in with a password."),
			boolean("enable_sign_up", "enableSignUp", "Whether users can sign up."),
			boolean("disable_self_signup", "disableSelfSignup", "Whether users are kept from signing up by themselves."),
			boolean("enable_guest_signin", "enableGuestSignin", "Whether users can sign in as a guest."),
			boolean("disable_signin", "disableSignin", "Whether signing in to the application is disabled."),
			boolean("enable_signin_session", "enableSigninSession", "Whether the sign-in session is kept in a cookie."),
			boolean("enable_auto_signin", "enableAutoSignin", "Whether users with a valid session are signed in automatically."),
			boolean("enable_exclusive_signin", "enableExclusiveSignin", "Whether a new sign-in signs the user out of the other sessions."),
			integer("max_sessions", "maxSessions", "The maximum number of concurrent sessions of a user in the application."),
			boolean("enable_code_signin", "enableCodeSignin", "Whether users can sign in with a verification code."),
			boolean("enable_web_authn", "enableWebAuthn", "Whether users can sign in with WebAuthn."),
			boolean("enable_link_with_email", "enableLinkWithEmail", "Whether a third-party account is linked to the user with the same email."),
			str("org_choice_mode", "orgChoiceMode", "How the organization is chosen on the sign-in page: empty, `None`, `Select` or `Input`."),
			boolean("is_shared", "isShared", "Whether the application, which must belong to the `built-in` organization, is shared with all organizations."),
			str("signup_url", "signupUrl", "A custom sign-up page URL."),
			str("signin_url", "signinUrl", "A custom sign-in page URL."),
			str("forget_url", "forgetUrl", "A custom forgot-password page URL."),
			str("affiliation_url", "affiliationUrl", "The affiliation URL."),
			str("terms_of_use", "termsOfUse", "The URL of the terms of use."),
			str("header_html", "headerHtml", "The HTML added to the head of the sign-in pages."),
			str("signup_html", "signupHtml", "The HTML shown on the sign-up page."),
			str("signin_html", "signinHtml", "The HTML shown on the sign-in page."),
			str("footer_html", "footerHtml", "The HTML of the footer."),
			str("form_css", "formCss", "The CSS of the sign-in form."),
			str("form_css_mobile", "formCssMobile", "The CSS of the sign-in form on mobile devices."),
			integer("form_offset", "formOffset", "The position of the sign-in form: 1 for left, 2 for center, 3 for right, 4 for center with the side panel."),
			str("form_side_html", "formSideHtml", "The HTML of the side panel."),
			str("form_background_url", "formBackgroundUrl", "The background image URL of the sign-in pages."),
			str("form_background_url_mobile", "formBackgroundUrlMobile", "The background image URL of the sign-in pages on mobile devices."),
			objList("signin_methods", "signinMethods", "The sign-in methods shown on the sign-in page.",
				str("name", "name", "The sign-in method, e.g. `Password`, `Verification code` or `WebAuthn`.").req(),
				str("display_name", "displayName", "The label of the method."),
				str("rule", "rule", "The rule of the method, e.g. `All`."),
			),
			str("saml_reply_url", "samlReplyUrl", "The assertion consumer service URL of the SAML service provider."),
			str("saml_single_logout_url", "samlSingleLogoutUrl", "The single logout URL of the SAML service provider."),
			str("saml_hash_algorithm", "samlHashAlgorithm", "The hash algorithm of the SAML signature: `SHA1`, `SHA256` or `SHA512`."),
			boolean("enable_saml_compress", "enableSamlCompress", "Whether the SAML response is compressed."),
			boolean("enable_saml_c14n10", "enableSamlC14n10", "Whether the SAML response is canonicalized with exclusive C14N 1.0."),
			str("saml_c14n_prefix", "samlC14nPrefix", "The namespace prefix list used with `enable_saml_c14n10`."),
			boolean("enable_saml_post_binding", "enableSamlPostBinding", "Whether the SAML response is sent with the HTTP POST binding."),
			boolean("disable_saml_attributes", "disableSamlAttributes", "Whether the user attributes are left out of the SAML response."),
			boolean("enable_saml_assertion_signature", "enableSamlAssertionSignature", "Whether the SAML assertion is signed."),
			boolean("use_email_as_saml_name_id", "useEmailAsSamlNameId", "Whether the email is used as the SAML NameID."),
			objList("saml_attributes", "samlAttributes", "The custom attributes added to the SAML response.",
				str("name", "name", "The name of the attribute.").req(),
				str("name_format", "nameFormat", "The name format of the attribute."),
				str("value", "value", "The value of the attribute."),
			),
			objList("providers", "providers", "The providers used by the application, e.g. identity providers for social sign-in, and email, SMS or captcha providers.",
				str("name", "name", "The name of the provider.").req(),
				str("owner", "owner", "The owner of the provider."),
				boolean("can_sign_up", "canSignUp", "Whether users can sign up with the provider."),
				boolean("can_sign_in", "canSignIn", "Whether users can sign in with the provider."),
				boolean("can_unlink", "canUnlink", "Whether users can unlink the provider from their account."),
				boolean("prompted", "prompted", "Whether users are prompted to link the provider."),
				str("rule", "rule", "The rule, e.g. `None`, `Dynamic`, `Always` or `All` depending on the provider category."),
			),
		},
	},
	{
		name:        "user",
		api:         "user",
		setPassword: true,
		ownerField:  orgOwner,
		description: "Manages a Casdoor user." + unmanagedNote,
		fields: []field{
			str("password", "password", "The password. Casdoor never returns it, so changes made outside of Terraform are not detected.").password(),
			str("display_name", "displayName", "The display name."),
			str("first_name", "firstName", "The first name."),
			str("last_name", "lastName", "The last name."),
			str("type", "type", "The user type, e.g. `normal-user`."),
			str("avatar", "avatar", "The avatar URL."),
			str("email", "email", "The email address."),
			boolean("email_verified", "emailVerified", "Whether the email address is verified."),
			str("phone", "phone", "The phone number, without the country calling code."),
			str("country_code", "countryCode", "The country code of the phone number, e.g. `US`."),
			str("region", "region", "The region."),
			str("location", "location", "The location."),
			str("affiliation", "affiliation", "The affiliation."),
			str("title", "title", "The title."),
			str("homepage", "homepage", "The homepage URL."),
			str("bio", "bio", "The bio."),
			str("tag", "tag", "The tag."),
			str("language", "language", "The language."),
			str("gender", "gender", "The gender."),
			str("birthday", "birthday", "The birthday."),
			str("external_id", "externalId", "The ID of the user in an external system."),
			strList("address", "address", "The address lines."),
			str("id_card_type", "idCardType", "The type of the ID card."),
			str("id_card", "idCard", "The ID card number."),
			str("real_name", "realName", "The real name."),
			boolean("is_verified", "isVerified", "Whether the real name is verified."),
			str("education", "education", "The education."),
			integer("score", "score", "The score."),
			integer("karma", "karma", "The karma."),
			integer("ranking", "ranking", "The ranking."),
			boolean("is_deleted", "isDeleted", "Whether the user is marked as deleted."),
			boolean("need_update_password", "needUpdatePassword", "Whether the user must change the password at the next sign-in."),
			str("ip_whitelist", "ipWhitelist", "The IP addresses or CIDRs the user can sign in from, separated by commas."),
			integer("uid_number", "uidNumber", "The POSIX UID published by the built-in LDAP server, 0 when not assigned."),
			str("signup_application", "signupApplication", "The application that the user signed up with."),
			boolean("is_admin", "isAdmin", "Whether the user is an administrator of the organization."),
			boolean("is_forbidden", "isForbidden", "Whether the user is forbidden to sign in."),
			strList("groups", "groups", "The groups of the user, in the `organization/group` format."),
			strMap("properties", "properties", "Custom properties."),
			str("user_id", "id", "The unique ID generated by Casdoor, used as the `sub` claim in tokens.").readOnly(),
		},
	},
	{
		name:        "provider",
		api:         "provider",
		ownerField:  adminOwner,
		description: "Manages a Casdoor provider: an identity provider for social sign-in, or an email, SMS, storage, payment or captcha service." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("category", "category", "The category, e.g. `OAuth`, `Email`, `SMS`, `Storage`, `SAML`, `Payment`, `Captcha` or `Web3`.").req(),
			str("type", "type", "The type within the category, e.g. `GitHub`, `Google`, `Custom` (OAuth), `SMTP` (Email) or `AWS S3` (Storage).").req(),
			str("sub_type", "subType", "The sub-type, used by some providers."),
			str("method", "method", "The method, used by some providers, e.g. `Normal` or `Silent` for OAuth."),
			str("client_id", "clientId", "The client ID, app key or username, depending on the type."),
			str("client_secret", "clientSecret", "The client secret, app secret or password, depending on the type.").secret(),
			str("client_id2", "clientId2", "The second client ID, used by some providers."),
			str("client_secret2", "clientSecret2", "The second client secret, used by some providers.").secret(),
			str("cert", "cert", "The name of the cert, used by some providers."),
			str("app_id", "appId", "The app ID, used by some providers."),
			str("host", "host", "The host, e.g. of an SMTP server."),
			integer("port", "port", "The port, e.g. of an SMTP server."),
			boolean("disable_ssl", "disableSsl", "Whether SSL is disabled."),
			str("ssl_mode", "sslMode", "The SSL mode of an email provider: `Auto`, `Enable` or `Disable`. Takes precedence over `disable_ssl`."),
			str("title", "title", "The email subject."),
			str("content", "content", "The email body or the content of the provider."),
			str("receiver", "receiver", "The test receiver."),
			str("region_id", "regionId", "The region ID."),
			str("sign_name", "signName", "The SMS signature name."),
			str("template_code", "templateCode", "The SMS template code."),
			str("endpoint", "endpoint", "The endpoint of the service."),
			str("intranet_endpoint", "intranetEndpoint", "The intranet endpoint of a storage service."),
			str("domain", "domain", "The domain or base URL of the service."),
			str("bucket", "bucket", "The bucket of a storage service."),
			str("path_prefix", "pathPrefix", "The path prefix in the bucket."),
			str("metadata", "metadata", "The SAML IdP metadata."),
			str("idp", "idP", "The certificate of the SAML IdP."),
			boolean("enable_sign_authn_request", "enableSignAuthnRequest", "Whether the SAML authentication request is signed."),
			str("issuer_url", "issuerUrl", "The issuer URL."),
			str("custom_auth_url", "customAuthUrl", "The authorization URL of a custom OAuth provider."),
			str("custom_token_url", "customTokenUrl", "The token URL of a custom OAuth provider."),
			str("custom_user_info_url", "customUserInfoUrl", "The user info URL of a custom OAuth provider."),
			str("custom_logout_url", "customLogoutUrl", "The logout URL of a custom OAuth provider."),
			str("custom_logo", "customLogo", "The logo URL of a custom provider."),
			str("scopes", "scopes", "The OAuth scopes, separated by spaces."),
			strMap("user_mapping", "userMapping", "How the user info fields of a custom OAuth provider map to Casdoor user fields, e.g. `id`, `username`, `displayName`, `email`, `avatarUrl`."),
			strMap("http_headers", "httpHeaders", "The HTTP headers sent by a custom HTTP email or SMS provider."),
			boolean("enable_pkce", "enablePkce", "Whether PKCE is used."),
			boolean("enable_proxy", "enableProxy", "Whether requests to the provider go through the proxy configured in Casdoor."),
			boolean("require_message_authenticator", "requireMessageAuthenticator", "Whether a RADIUS provider requires the Message-Authenticator attribute."),
			str("state", "state", "The state of the provider, `Enabled` or `Disabled`."),
			str("email_regex", "emailRegex", "Only emails matching this regular expression can sign in with the provider."),
			str("provider_url", "providerUrl", "The URL of the provider's console."),
		},
	},
	{
		name:        "cert",
		api:         "cert",
		ownerField:  adminOwner,
		description: "Manages a Casdoor cert, the key pair that signs tokens. Casdoor generates the certificate and private key when they are not set." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("scope", "scope", "The scope, `JWT` or `CA`."),
			str("type", "type", "The type, e.g. `x509`."),
			str("crypto_algorithm", "cryptoAlgorithm", "The algorithm, e.g. `RS256`, `RS512`, `ES256`, `ES512` or `PS256`."),
			integer("bit_size", "bitSize", "The key size in bits, e.g. `4096` for RS256."),
			integer("expire_in_years", "expireInYears", "The validity of the certificate, in years."),
			str("certificate", "certificate", "The PEM-encoded certificate."),
			str("private_key", "privateKey", "The PEM-encoded private key.").secret(),
		},
	},
	{
		name:        "role",
		api:         "role",
		ownerField:  orgOwner,
		description: "Manages a Casdoor role." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("description", "description", "The description."),
			strList("users", "users", "The users of the role, in the `organization/user` format."),
			strList("groups", "groups", "The groups of the role, in the `organization/group` format."),
			strList("roles", "roles", "The sub-roles inherited by the role, in the `organization/role` format."),
			strList("domains", "domains", "The domains."),
			boolean("is_enabled", "isEnabled", "Whether the role is enabled."),
		},
	},
	{
		name:        "permission",
		api:         "permission",
		ownerField:  orgOwner,
		description: "Manages a Casdoor permission, a Casbin policy that grants users, groups or roles actions on resources." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("description", "description", "The description."),
			strList("users", "users", "The users, in the `organization/user` format."),
			strList("groups", "groups", "The groups, in the `organization/group` format."),
			strList("roles", "roles", "The roles, in the `organization/role` format."),
			strList("domains", "domains", "The domains."),
			str("model", "model", "The name of the Casbin model."),
			str("adapter", "adapter", "The name of the adapter that stores the policies."),
			str("resource_type", "resourceType", "The resource type, e.g. `Application`, `TreeNode` or `Custom`."),
			strList("resources", "resources", "The resources."),
			strList("actions", "actions", "The actions, e.g. `Read`, `Write` or `Admin`."),
			str("effect", "effect", "The effect, `Allow` or `Deny`."),
			str("state", "state", "The approval state, `Approved` or `Pending`. Only approved permissions take effect."),
			boolean("is_enabled", "isEnabled", "Whether the permission is enabled."),
		},
	},
	{
		name:        "group",
		api:         "group",
		ownerField:  orgOwner,
		description: "Manages a Casdoor group." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("manager", "manager", "The manager of the group."),
			str("contact_email", "contactEmail", "The contact email."),
			str("type", "type", "The type, `Virtual` or `Physical`."),
			str("parent_id", "parentId", "The name of the parent group, or the organization name for a top-level group."),
			boolean("is_top_group", "isTopGroup", "Whether the group is a top-level group."),
			integer("gid_number", "gidNumber", "The POSIX GID published by the built-in LDAP server, 0 when not assigned."),
			strMap("properties", "properties", "Custom properties."),
			boolean("is_enabled", "isEnabled", "Whether the group is enabled."),
		},
	},
	{
		name:        "model",
		api:         "model",
		ownerField:  orgOwner,
		description: "Manages a Casdoor model, the Casbin model used by permissions and enforcers." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("description", "description", "The description."),
			str("model_text", "modelText", "The Casbin model, in the Casbin CONF format."),
		},
	},
	{
		name:        "adapter",
		api:         "adapter",
		ownerField:  orgOwner,
		description: "Manages a Casdoor adapter, the Casbin adapter that stores the policies of permissions and enforcers." + unmanagedNote,
		fields: []field{
			str("table", "table", "The table that stores the policies."),
			boolean("use_same_db", "useSameDb", "Whether the policies are stored in the database of Casdoor, so that the connection settings below are not needed."),
			str("type", "type", "The type of the adapter."),
			str("database_type", "databaseType", "The database type, e.g. `mysql` or `postgres`."),
			str("host", "host", "The host of the database."),
			integer("port", "port", "The port of the database."),
			str("user", "user", "The user of the database."),
			str("password", "password", "The password of the database.").secret(),
			str("database", "database", "The name of the database."),
		},
	},
	{
		name:        "enforcer",
		api:         "enforcer",
		ownerField:  orgOwner,
		description: "Manages a Casdoor enforcer, a Casbin enforcer built from a model and an adapter." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("description", "description", "The description."),
			str("model", "model", "The model, in the `organization/model` format."),
			str("adapter", "adapter", "The adapter, in the `organization/adapter` format."),
		},
	},
	{
		name:        "invitation",
		api:         "invitation",
		ownerField:  orgOwner,
		description: "Manages a Casdoor invitation, the code that lets users sign up to an application." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("code", "code", "The invitation code, which can be a regular expression that matches several codes."),
			str("default_code", "defaultCode", "The code filled in on the sign-up page when `code` is a regular expression."),
			integer("quota", "quota", "The number of times the invitation can be used."),
			integer("used_count", "usedCount", "The number of times the invitation has been used.").readOnly(),
			str("application", "application", "The application that the invitation is for, or `All`."),
			str("username", "username", "The username that the invited user must sign up with."),
			str("email", "email", "The email that the invited user must sign up with."),
			str("phone", "phone", "The phone number that the invited user must sign up with."),
			str("signup_group", "signupGroup", "The group that the invited users are added to."),
			str("expire_time", "expireTime", "The time when the invitation expires, in the RFC 3339 format."),
			str("state", "state", "The state, e.g. `Active`."),
		},
	},
	{
		name:        "syncer",
		api:         "syncer",
		adminOwned:  true,
		description: "Manages a Casdoor syncer, which synchronizes the users of an organization with an external database or system." + unmanagedNote,
		fields: []field{
			str("organization", "organization", "The organization whose users are synchronized.").req(),
			str("type", "type", "The type of the source, e.g. `Database` or `Keycloak`."),
			str("database_type", "databaseType", "The database type, e.g. `mysql`, `postgres` or `mssql`."),
			str("ssl_mode", "sslMode", "The SSL mode of the database connection."),
			str("host", "host", "The host of the source."),
			integer("port", "port", "The port of the source."),
			str("user", "user", "The user of the source."),
			str("password", "password", "The password of the source.").secret(),
			str("ssh_type", "sshType", "How the SSH tunnel authenticates, empty when no tunnel is used."),
			str("ssh_host", "sshHost", "The host of the SSH tunnel."),
			integer("ssh_port", "sshPort", "The port of the SSH tunnel."),
			str("ssh_user", "sshUser", "The user of the SSH tunnel."),
			str("ssh_password", "sshPassword", "The password of the SSH tunnel.").secret(),
			str("cert", "cert", "The name of the cert used by the SSH tunnel."),
			str("database", "database", "The name of the database."),
			str("table", "table", "The table that holds the users."),
			objList("table_columns", "tableColumns", "How the columns of the table map to Casdoor user fields.",
				str("name", "name", "The name of the column.").req(),
				str("type", "type", "The type of the column, e.g. `string`, `integer` or `boolean`."),
				str("casdoor_name", "casdoorName", "The Casdoor user field, e.g. `Name`, `DisplayName` or `Email`."),
				boolean("is_key", "isKey", "Whether the column identifies the user."),
				boolean("is_hashed", "isHashed", "Whether the column is included in the hash that detects changes."),
				strList("values", "values", "The values of the column."),
			),
			str("affiliation_table", "affiliationTable", "The table that holds the affiliations."),
			str("avatar_base_url", "avatarBaseUrl", "The base URL prepended to the avatars."),
			integer("sync_interval", "syncInterval", "The number of seconds between two synchronizations."),
			boolean("is_read_only", "isReadOnly", "Whether the source is only read, so that changes in Casdoor are not written back."),
			boolean("is_enabled", "isEnabled", "Whether the syncer is enabled."),
		},
	},
	{
		name:        "webhook",
		api:         "webhook",
		adminOwned:  true,
		description: "Manages a Casdoor webhook, which sends the events of an organization to a URL." + unmanagedNote,
		fields: []field{
			str("organization", "organization", "The organization whose events are sent.").req(),
			str("url", "url", "The URL that receives the events."),
			str("method", "method", "The HTTP method, e.g. `POST`."),
			str("content_type", "contentType", "The content type of the request, `application/json` or `application/x-www-form-urlencoded`."),
			objList("headers", "headers", "The HTTP headers added to the request.",
				str("name", "name", "The name of the header.").req(),
				str("value", "value", "The value of the header."),
			),
			strList("events", "events", "The events that are sent, e.g. `signup`, `login`, `logout` or `update-user`."),
			strList("token_fields", "tokenFields", "The token fields included in the request."),
			strList("object_fields", "objectFields", "The fields of the object included in the request, `All` includes everything."),
			boolean("is_user_extended", "isUserExtended", "Whether the user who triggered the event is included in the request."),
			boolean("single_org_only", "singleOrgOnly", "Whether only events of the organization itself are sent."),
			integer("max_retries", "maxRetries", "The number of times a failed delivery is retried."),
			integer("retry_interval", "retryInterval", "The number of seconds between two retries."),
			boolean("use_exponential_backoff", "useExponentialBackoff", "Whether the retry interval grows exponentially."),
			boolean("is_enabled", "isEnabled", "Whether the webhook is enabled."),
		},
	},
	{
		name:        "key",
		api:         "key",
		ownerField:  orgOwner,
		description: "Manages a Casdoor key, an access key and secret that calls the Casdoor API on behalf of an organization, an application or a user." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("type", "type", "What the key belongs to: `Organization`, `Application`, `User` or `General`."),
			str("organization", "organization", "The organization that the key belongs to."),
			str("application", "application", "The application that the key belongs to."),
			str("user", "user", "The user that the key belongs to."),
			str("access_key", "accessKey", "The access key."),
			str("access_secret", "accessSecret", "The access secret.").secret(),
			str("expire_time", "expireTime", "The time when the key expires, in the RFC 3339 format."),
			str("state", "state", "The state, e.g. `Active`."),
		},
	},
	{
		name:        "product",
		api:         "product",
		ownerField:  orgOwner,
		description: "Manages a Casdoor product, an item that users can buy." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("image", "image", "The image URL."),
			str("detail", "detail", "The detail."),
			str("description", "description", "The description."),
			str("tag", "tag", "The tag."),
			str("currency", "currency", "The currency, e.g. `USD`."),
			float("price", "price", "The price."),
			integer("quantity", "quantity", "The quantity in stock."),
			integer("sold", "sold", "The quantity sold."),
			boolean("is_recharge", "isRecharge", "Whether the product recharges the balance of the user."),
			boolean("disable_custom_recharge", "disableCustomRecharge", "Whether users are kept from entering a custom recharge amount."),
			strList("providers", "providers", "The names of the payment providers."),
			str("success_url", "successUrl", "The URL that the user is sent to after paying."),
			str("state", "state", "The state, `Published` or `Draft`."),
			strMap("properties", "properties", "Custom properties."),
		},
	},
	{
		name:        "plan",
		api:         "plan",
		ownerField:  orgOwner,
		description: "Manages a Casdoor plan, a recurring price that users subscribe to." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("description", "description", "The description."),
			float("price", "price", "The price per period."),
			str("currency", "currency", "The currency, e.g. `USD`."),
			str("period", "period", "The billing period, `Monthly` or `Yearly`."),
			str("product", "product", "The product that is bought when subscribing to the plan."),
			strList("payment_providers", "paymentProviders", "The names of the payment providers."),
			boolean("is_enabled", "isEnabled", "Whether the plan is enabled."),
			boolean("is_exclusive", "isExclusive", "Whether a user can have at most one subscription of the plan."),
			str("role", "role", "The role that subscribers get."),
			strList("options", "options", "The features listed on the pricing page."),
		},
	},
	{
		name:        "pricing",
		api:         "pricing",
		ownerField:  orgOwner,
		description: "Manages a Casdoor pricing, the pricing page that offers a set of plans." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("description", "description", "The description."),
			strList("plans", "plans", "The plans offered, in the `organization/plan` format."),
			boolean("is_enabled", "isEnabled", "Whether the pricing is enabled."),
			integer("trial_duration", "trialDuration", "The length of the free trial, in days."),
			str("application", "application", "The application that users sign up to."),
		},
	},
	{
		name:        "subscription",
		api:         "subscription",
		ownerField:  orgOwner,
		description: "Manages a Casdoor subscription of a user to a plan." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("description", "description", "The description."),
			str("user", "user", "The name of the user."),
			str("pricing", "pricing", "The name of the pricing."),
			str("plan", "plan", "The name of the plan."),
			str("payment", "payment", "The name of the payment."),
			str("start_time", "startTime", "The time when the subscription starts, in the RFC 3339 format."),
			str("end_time", "endTime", "The time when the subscription ends, in the RFC 3339 format."),
			str("period", "period", "The billing period, `Monthly` or `Yearly`."),
			str("state", "state", "The state: `Pending`, `Error`, `Suspended`, `Active`, `Upcoming` or `Expired`."),
		},
	},
	{
		name:        "coupon",
		api:         "coupon",
		ownerField:  orgOwner,
		description: "Manages a Casdoor coupon, a discount code for orders." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("description", "description", "The description."),
			str("code", "code", "The coupon code."),
			str("discount_type", "discountType", "The discount type, `percentage` or `fixed`."),
			float("discount", "discount", "The discount: a percentage from 0 to 100, or a fixed amount."),
			float("max_discount", "maxDiscount", "The maximum discount of a percentage coupon, 0 means unlimited."),
			str("scope", "scope", "What the coupon applies to: `universal`, `product` or `user`."),
			strList("products", "products", "The products that the coupon applies to when the scope is `product`."),
			strList("users", "users", "The users that the coupon applies to when the scope is `user`."),
			integer("quantity", "quantity", "The number of times the coupon can be used in total, 0 means unlimited."),
			integer("used_count", "usedCount", "The number of times the coupon has been used.").readOnly(),
			integer("max_usage_per_user", "maxUsagePerUser", "The number of times a user can use the coupon, 0 means unlimited."),
			str("start_time", "startTime", "The time when the coupon becomes valid, in the RFC 3339 format."),
			str("expire_time", "expireTime", "The time when the coupon expires, in the RFC 3339 format."),
			float("min_order_amount", "minOrderAmount", "The minimum order amount that the coupon applies to."),
			str("currency", "currency", "The currency, e.g. `USD`."),
			str("state", "state", "The state: `Active`, `Inactive` or `Expired`."),
		},
	},
	{
		name:        "agent",
		api:         "agent",
		ownerField:  orgOwner,
		description: "Manages a Casdoor agent." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("url", "url", "The URL of the agent."),
			str("token", "token", "The token used to call the agent.").secret(),
			str("application", "application", "The application of the agent."),
		},
	},
	{
		name:        "server",
		api:         "server",
		ownerField:  orgOwner,
		description: "Manages a Casdoor server, an MCP server whose tools are made available through Casdoor." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("url", "url", "The URL of the MCP server."),
			str("token", "token", "The token used to call the MCP server.").secret(),
			str("application", "application", "The application of the server."),
		},
	},
	{
		name:        "rule",
		api:         "rule",
		ownerField:  orgOwner,
		description: "Manages a Casdoor rule, a web application firewall rule applied by sites." + unmanagedNote,
		fields: []field{
			str("type", "type", "The type of the rule, e.g. `User-Agent`."),
			objList("expressions", "expressions", "The expressions that a request is matched against.",
				str("name", "name", "The name of the expression.").req(),
				str("operator", "operator", "The operator."),
				str("value", "value", "The value."),
			),
			str("action", "action", "What happens to a matching request, e.g. `Block`."),
			integer("status_code", "statusCode", "The HTTP status code returned to a blocked request."),
			str("reason", "reason", "The message returned to a blocked request."),
			boolean("is_verbose", "isVerbose", "Whether the response explains which rule matched."),
		},
	},
	{
		name:        "site",
		api:         "site",
		ownerField:  orgOwner,
		description: "Manages a Casdoor site, a domain served by the built-in reverse proxy and web application firewall." + unmanagedNote,
		fields: []field{
			str("display_name", "displayName", "The display name."),
			str("tag", "tag", "The tag."),
			str("domain", "domain", "The domain of the site."),
			strList("other_domains", "otherDomains", "The other domains of the site."),
			boolean("need_redirect", "needRedirect", "Whether the other domains are redirected to the domain."),
			boolean("disable_verbose", "disableVerbose", "Whether responses to blocked requests leave out the details."),
			strList("rules", "rules", "The rules applied to the site, in the `organization/rule` format."),
			boolean("enable_alert", "enableAlert", "Whether alerts are sent when the site is down."),
			integer("alert_interval", "alertInterval", "The number of seconds between two health checks."),
			integer("alert_try_times", "alertTryTimes", "The number of failed health checks before an alert is sent."),
			strList("alert_providers", "alertProviders", "The names of the providers that send the alerts."),
			str("host", "host", "The upstream that requests are forwarded to."),
			integer("port", "port", "The port of the upstream on the local machine, used when `host` is empty."),
			strList("hosts", "hosts", "The upstreams that requests are balanced between."),
			str("ssl_mode", "sslMode", "The SSL mode, `HTTP`, `HTTPS and HTTP`, `HTTPS Only` or `Static Folder`."),
			str("ssl_cert", "sslCert", "The name of the cert served for the domain."),
			str("public_ip", "publicIp", "The public IP address that the domain resolves to."),
			str("casdoor_application", "casdoorApplication", "The application that users must sign in to before reaching the site."),
		},
	},
}
